version: 2.1
jobs:
  build:
    working_directory: ~/client
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
      - run:
          name: Run Tests
          command: npm run test
