version: 2
jobs:
  build:
    working_directory: ~/client
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: cd client/; ls -la; pwd;
      - restore_cache:
          key: npm-cache-v1-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: npm-cache-v1-{{ checksum "package.json" }}
          paths:
            - /home/circleci/.npm
      - run:
          name: Run Tests
          command: npm run test
